site_name: About Me
site_url: https://theeman05.github.io/AboutMe/
repo_name: theeman05/AboutMe

theme:
  name: material
  highlightjs: true
  hljs_style: github-dark
  palette:
    scheme: slate
    primary: pink

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Home: index.md
- Experience: experience.md
- Courses: courses.md
- Projects: projects.md
- Resources: resources.md